### ISSUE TITLE
[IDEA] Collaborate / integrate with https://github.com/AlexTatiyants/pev ?

### ISSUE THREAD

**Issue by gvankeerberghen** [mgartner/pg_flame#2]
This looks nice and potentially very useful, congrats!

I've personally used the [Postgres Explain Visualizer](https://tatiyants.com/pev/#/plans) of @AlexTatiyants, whose code is hosted here https://github.com/AlexTatiyants/pev, in the past and found it very useful to grasp plans and reveal leads to improve queries or data models.

So as an idea, integrating your two solutions into one website could potentially make both even better and useful.

Cheers

**Comment by gvankeerberghen** [comment]
Follow-up: the above PEV might have been abandoned but here's an active successor (found in the HN comments) https://github.com/dalibo/pev2

**Comment by kokes** [comment]
The beauty of PEV is that it's all done on the client, there is no server side component.

I have replicated some of this repo's functionality in client-side JavaScript (see [pg_flame.js](https://github.com/kokes/pg_flame.js)), that solution might be more easily embeddable.

**Comment by mgartner** [comment]
Cool to see a JS-only implementation! Definitely useful, just depends on your workflow if you'd prefer that over a CLI.

I'm going to close this as I don't see any action items I can take at the moment. But I'm always open to any sort of collaboration.
