### ISSUE TITLE
Please publish pre-built docker images on Docker Hub

### ISSUE THREAD

**Issue by Envek** [mgartner/pg_flame#5]
It would be much easier to use your absolutely awesome tool if you publish Docker images for every release into any public Docker registry (it doesn't really matter will it be [hub.docker.com](https://hub.docker.com/) or [quay.io](https://quay.io/)), and provide links to it in the README, like this:

```sh
docker pull mgartner/pg_flame # or docker pull quay.io/mgartner/pg_flame
psql dbname -qAtc 'EXPLAIN (…) SELECT …'  | docker run --rm -i mgartner/pg_flame > flamegraph.html
```

Flamegraphs are the best! Thank you for creating pg_flame!

**Comment by mgartner** [comment]
Good idea. I've created `mgartner/pg_flame` on hub.docker.com: https://hub.docker.com/repository/docker/mgartner/pg_flame

I've also updated the README show the `docker pull mgartner/pg_flame` command.
